name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Initialize custom bot
        id: bot
        uses: starburst997/custom-bot-init@v1
        with:
          app-id: ${{ secrets.BOT_ID }}
          private-key: ${{ secrets.BOT_KEY }}

      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          token: ${{ steps.bot.outputs.token }}

      - name: Auto Version and Tag
        id: version
        uses: ./
        with:
          update-major-minor: true
          git-config: false

      - name: Generate changelog and create release
        uses: starburst997/commits-logs@v1
        with:
          token: ${{ steps.bot.outputs.token }}
