name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Auto Version and Tag
        id: version
        uses: ./
        with:
          update-major-minor: true

      - name: Generate changelog and create release
        uses: starburst997/commits-logs@v1
        with:
          format: grouped
          create-release: true
